[package]
name = "itinera-core"
description = "The core of Itinera, a workflow framework that keeps business rules separate from flow control."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[features]
async = []
unstable = []

[dependencies]
serde.workspace = true
erased-serde.workspace = true
derive_more.workspace = true

[dev-dependencies]
futures = { workspace = true, features = ["executor"] }
itinera = { path = "../itinera", default-features = false, features = ["unstable", "async"] }
serde_json.workspace = true

[lints]
workspace = true
